name: Quick Check

on:
  pull_request:
    branches: [ main, develop ]

env:
  FLUTTER_VERSION: '3.32.5'
  JAVA_VERSION: '21'

jobs:
  quick_check:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Cache pub dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
        key: ${{ runner.os }}-quick-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-quick-pub-
        
    - name: Get dependencies
      run: flutter pub get
        
    - name: Verify code formatting
      run: |
        echo "检查代码格式..."
        if ! dart format --output=none --set-exit-if-changed .; then
          echo "❌ 代码格式不正确"
          echo "请运行 'make format' 或 'dart format .' 修复格式问题"
          exit 1
        fi
        echo "✅ 代码格式正确"
        
    - name: Run static analysis
      run: |
        echo "运行静态分析..."
        dart analyze --fatal-infos
        echo "✅ 静态分析通过"
        
    - name: Run tests
      run: |
        echo "运行测试..."
        flutter test --reporter=compact
        echo "✅ 测试通过"
        
    - name: Check build readiness
      run: |
        echo "检查构建准备..."
        flutter build apk --debug --target-platform android-arm64
        echo "✅ 构建检查通过" 